import os, sys

# 스크립트 위치(frontend/scripts) 기준 레포 상대경로
_script_dir = os.path.dirname(os.path.abspath(__file__))
_repo_root = os.path.abspath(os.path.join(_script_dir, '..', '..'))
source_dir = os.path.join(_repo_root, 'lectures')
output_file = os.path.join(_repo_root, 'frontend', 'src', 'data', 'lectureContents.ts')

lecture_contents = {}
for root, dirs, files in os.walk(source_dir):
    dirs.sort()  # 결정적 출력 순서
    for file in sorted(files):
        if file.endswith('.md') and 'backup' not in file:
            file_path = os.path.join(root, file)
            rel_path = os.path.relpath(file_path, source_dir).replace('\\', '/')
            try:
                with open(file_path, 'r', encoding='utf-8') as f:
                    content = f.read()
                # JS 템플릿 리터럴 이스케이프
                content = content.replace('\\', '\\\\').replace('`', '\\`').replace('${', '\\${')
                lecture_contents[rel_path] = content
                print(f'  OK: {rel_path}')
            except Exception as e:
                print(f'  ERR: {rel_path}: {e}')

print(f'\n총 {len(lecture_contents)}개 파일')

with open(output_file, 'w', encoding='utf-8') as f:
    f.write('// Auto-generated file - DO NOT EDIT MANUALLY\n')
    f.write('// Generated by scripts/gen_contents.py\n\n')
    f.write('export const LECTURE_CONTENTS: Record<string, string> = {\n')
    items = list(lecture_contents.items())
    for idx, (path, content) in enumerate(items):
        comma = ',' if idx < len(items) - 1 else ''
        f.write(f'  "{path}": `{content}`{comma}\n')
    f.write('}\n')

print(f'완료: {output_file}')
print(f'크기: {os.path.getsize(output_file) / 1024:.1f} KB')
