import os
import json
import sys

def escape_string(s):
    """문자열을 JavaScript/TypeScript에서 사용 가능하도록 이스케이프"""
    s = s.replace('\\', '\\\\')
    s = s.replace('`', '\\`')
    s = s.replace('${', '\\${')
    return s

def generate_lecture_contents(source_dir, output_file):
    """마크다운 파일들을 읽어서 TypeScript 파일로 변환"""

    print(f"Scanning directory: {source_dir}")

    lecture_contents = {}

    # lectures 폴더 스캔
    for root, dirs, files in os.walk(source_dir):
        for file in files:
            if file.endswith('.md'):
                file_path = os.path.join(root, file)
                # 상대 경로 계산 (lectures/ 기준)
                rel_path = os.path.relpath(file_path, source_dir)
                # Windows 경로를 Unix 스타일로 변환
                rel_path = rel_path.replace('\\', '/')

                print(f"  Reading: {rel_path}")

                try:
                    with open(file_path, 'r', encoding='utf-8') as f:
                        content = f.read()
                        lecture_contents[rel_path] = escape_string(content)
                except Exception as e:
                    print(f"  ERROR reading {rel_path}: {e}")

    print(f"\nTotal files processed: {len(lecture_contents)}")

    # TypeScript 파일 생성
    print(f"Writing to: {output_file}")

    with open(output_file, 'w', encoding='utf-8') as f:
        f.write('// Auto-generated file - DO NOT EDIT MANUALLY\n')
        f.write('// Generated by scripts/generate_lecture_contents.py\n\n')
        f.write('export const LECTURE_CONTENTS: Record<string, string> = {\n')

        for idx, (path, content) in enumerate(lecture_contents.items()):
            f.write(f'  "{path}": `{content}`')
            if idx < len(lecture_contents) - 1:
                f.write(',\n')
            else:
                f.write('\n')

        f.write('}\n')

    print(f"Successfully generated {output_file}")
    print(f"File size: {os.path.getsize(output_file) / 1024:.2f} KB")

if __name__ == '__main__':
    # 스크립트 위치 기준으로 경로 계산
    script_dir = os.path.dirname(os.path.abspath(__file__))
    frontend_dir = os.path.dirname(script_dir)

    # 메인 서버용 - backend의 lectures 폴더 경로
    project_root = os.path.dirname(frontend_dir)
    source_dir = os.path.join(project_root, 'backend', 'static', 'lectures')

    # 출력 파일 경로
    output_file = os.path.join(frontend_dir, 'src', 'data', 'lectureContents.ts')

    print("=" * 60)
    print("Markdown to TypeScript Converter")
    print("=" * 60)
    print(f"Source: {source_dir}")
    print(f"Output: {output_file}")
    print("=" * 60 + "\n")

    if not os.path.exists(source_dir):
        print(f"ERROR: Source directory not found: {source_dir}")
        sys.exit(1)

    generate_lecture_contents(source_dir, output_file)

    print("\n" + "=" * 60)
    print("DONE!")
    print("=" * 60)
